name: BioTech
author: RelativoBR e Wilian
description: SlimeFun custom BioTech com novas maquina e itens
main: br.com.ohanacraft.biotech.BioTech
website: https://loja.ohanacraft.com.br/
depend: [Slimefun]
version: ${project.version}
api-version: 1.18