name: BioTech
author: RelativoBR e Wilian
description: SlimeFun custom BioTech new machine and resources
main: br.com.ohanacraft.biotech.BioTech
website: https://loja.ohanacraft.com.br/
depend: [Slimefun, SupremeExpansion]
version: ${project.version}
api-version: 1.18